crowdin_api/requester.py, crowdin_api/tests/test_requester.py
At the moment, there is no way to pass arguments to the `requests` package, for example `verify` or `proxies`. This pull request allows the user to pass such parameters over the crowdin client.
=> allow keywords parameters to be passed to requests API

crowdin_api/api_resources/translations/resource.py
it shoule be targetLanguageIds, not targetLanguageId
=> fix build project directory translation param error

crowdin_api/api_resources/labels/resource.py, crowdin_api/api_resources/labels/tests/test_labels_resources.py
Fixed paths in labels.assign/unassign label from strings methods to include the "/strings" suffix
=> Fix Assign/unassign label from strings paths

crowdin_api/api_resources/translations/resource.py
=> Change buildId type to int in download_project_translations

README.md, crowdin_api/client.py, crowdin_api/tests/test_client.py
Implements a possible solution for #20
=> Move config parameters from class to instance #20

crowdin_api/api_resources/distributions/tests/test_distributions_resources.py, crowdin_api/api_resources/translation_memory/__init__.py, crowdin_api/api_resources/users/__init__.py, crowdin_api/api_resources/users/tests/test_users_resources.py, crowdin_api/api_resources/workflows/tests/test_workflows_resources.py, crowdin_api/enums.py, crowdin_api/tests/test_client.py, crowdin_api/tests/test_requester.py, requirements/requirements-dev.txt, requirements/requirements.txt
update xenon package 
update code for lint style code
=> Fix bug flake8

crowdin_api/api_resources/projects/enums.py, crowdin_api/api_resources/projects/resource.py, crowdin_api/api_resources/projects/tests/test_projects_resources.py, crowdin_api/api_resources/projects/types.py, crowdin_api/api_resources/source_files/enums.py
add project file formats endpoints
add docstring for EscapeQuotes enum
=> Add project file formats endpoints

README.md, crowdin_api/api_resources/source_files/types.py, crowdin_api/client.py, crowdin_api/requester.py, crowdin_api/tests/test_client.py, crowdin_api/tests/test_requester.py
add EXTENDED_REQUEST_PARAMS for CrowdinClient class
fix type for srxStorageId attribute into Request model source_files API
Fixes #65, #66
=> Add extended params for request

crowdin_api/api_resources/bundles/resource.py, crowdin_api/api_resources/bundles/tests/test_bundles_resources.py
Created the new bundle functions as mentioned by #70
I am new to unit testing in Python so these unit tests are what I could manage by looking at the existing tests.
=> Added 3 new bundle functions with basic unit tests

crowdin_api/requester.py, crowdin_api/tests/test_requester.py
Closes https://github.com/crowdin/crowdin-api-client-python/issues/84
Since 2023-05-30, crowdin API responses with error on any GET request (like. `list_files` or `list_projects`)
```
crowdin_api.exceptions.ValidationError: ValidationError: http_status=400, request_id=None, detail: None, context=b'{"error":{"message":"Incorrect json in request body. No error","code":400}}'
```
The problem is what we send "null" string in body on every GET request, caused by this code
https://github.com/crowdin/crowdin-api-client-python/blob/81e43ef9139b8acbe7c2d2b6e0c915927e4e0e7b/crowdin_api/requester.py#L118
Propose is to change with logic -- if method `request()` called without request_data, we sends no body at all. It correlates with API documentation (for example …
=> Fix sends "null" in GET request body

.github/workflows/docs.yml, .github/workflows/pypi.yml, .github/workflows/python-package.yml, requirements/requirements-dev.txt, setup.cfg
- The versions are taken according PyPIs latest version
- Fixes: #100 
- The test are passing in my local environment
=> fix: Bumped up the dependency versions

crowdin_api/api_resources/projects/tests/test_projects_resources.py
- Suggested in : [#105 (review)](https://github.com/crowdin/crowdin-api-client-python/pull/105#pullrequestreview-1628425334)
=> test: String Exporter Settings API

crowdin_api/api_resources/source_strings/enums.py, crowdin_api/api_resources/source_strings/resource.py, crowdin_api/api_resources/source_strings/tests/test_source_strings_resources.py, crowdin_api/api_resources/source_strings/types.py
=> feat: Support for String Batch Operation

crowdin_api/api_resources/tasks/enums.py, crowdin_api/api_resources/tasks/resource.py, crowdin_api/api_resources/tasks/tests/test_tasks_resources.py
- Added other missing params
- Added missing functions
- fixes: #88
=> feat: Support for `includePreTranslatedStringsOnly`

crowdin_api/api_resources/labels/resource.py, crowdin_api/api_resources/labels/tests/test_labels_resources.py
=> feat(labels): add the Screenshot Labels management APIs

crowdin_api/client.py, crowdin_api/tests/test_client.py
👋 I found a small issue while sending translations via the api this afternoon
- Bind `MAX_RETRY` + `RETRY_DELAY` to the api requestor
- Update default test
- Add a test with custom values
My current config:
```python
return CrowdinClient(
organization=self.organization, token=self.token, timeout=600, retry_delay=10
```
```sh
INFO:[requester.py] Initiating retry 1 for request post projects/xxx/translations after sleeping 0.1 seconds.
```
It doesn't use our custom values cf:
```sh
retry_delay=0.1 timeout=600 max_retries=5
```
It takes the values we specified cf:
```sh
retry_delay=10 timeout=600 max_retries=5
```
=> fix(api-requestor): bind custom values for max_retry and retry_delay

crowdin_api/api_resources/source_strings/resource.py, crowdin_api/api_resources/source_strings/tests/test_source_strings_resources.py
The add_string method is missing the option to add a branch ID which is required when uploading strings to a string based project in Crowdin.
=> fix(source_strings): add branch id parameter to add_string

crowdin_api/api_resources/__init__.py, crowdin_api/api_resources/ai/__init__.py, crowdin_api/api_resources/ai/enums.py, crowdin_api/api_resources/ai/resource.py, crowdin_api/api_resources/ai/tests/test_ai_resources.py, crowdin_api/api_resources/ai/types.py, crowdin_api/client.py, crowdin_api/tests/test_client.py
=> feat(ai): support for AI resource

crowdin_api/api_resources/screenshots/resource.py, crowdin_api/api_resources/screenshots/tests/test_screenshots_resources.py
=> feat(screenshots): added parameter and deprecation warning

crowdin_api/api_resources/translation_status/resource.py, crowdin_api/api_resources/translation_status/tests/test_translation_status_resources.py
This PR fixes the endpoint URL in the `list_qa_check_issues()` method.
I guess that the code was originally copy-pasted from the `get_project_progress()` method, but the URL wasn't updated.
The endpoint in the JS client library is [here](https://github.com/crowdin/crowdin-api-client-js/blob/master/src/translationStatus/index.ts#L234).
=> fix(translation_status): Fix list_qa_check_issues endpoint URL

crowdin_api/api_resources/translations/resource.py, crowdin_api/api_resources/translations/tests/test_translations_resources.py, crowdin_api/api_resources/translations/types.py
The support for addToTm parameter has been added to upload_translation method:
- Defined addToTm in UploadTranslationRequest type
- Added addToTm as optional boolean parameter in upload_translation
- Added comprehensive test cases covering all possible scenarios
Default value (true) is handled by the API as specified in: https://developer.crowdin.com/api/v2/#operation/api.projects.translations.postOnLanguage
Closes #183
=> feat: add addToTm parameter support for Upload Translation API

crowdin_api/api_resources/glossaries/resource.py, crowdin_api/api_resources/glossaries/tests/test_glossaries_resources.py
Added support for filtering terms using CroQL query parameter in the List Terms API endpoint.
Changes:
- Added croql parameter to list_terms method
- Updated test suite with new test cases for CroQL filtering
- Maintained compatibility with existing query parameters
Closes #182
=> feat(api): Add croql parameter support to List Terms API

README.md, crowdin_api/client.py, crowdin_api/tests/test_client.py
-Add GraphQL method to CrowdinClient for interfacing with the GraphQL endpoint.
-The implementation supports query strings and optional variables.
-Includes comprehensive test coverage for request validation.
Implements #180
=> feat: add support for GraphQL endpoint

crowdin_api/api_resources/reports/enums.py, crowdin_api/api_resources/reports/resource.py, crowdin_api/api_resources/reports/tests/test_reports_resources.py
This PR adds support for the new Pre-Translate Efficiency Report. More information about this Report type can be found in the [API documentation](https://support.crowdin.com/developer/api/v2/#tag/Reports/operation/api.projects.reports.post).
Closes #168
=> feat(api): Add Pre-Translate Accuracy Report

crowdin_api/api_resources/reports/resource.py, crowdin_api/api_resources/reports/tests/test_reports_resources.py
Implemented User Report Settings Templates endpoints to complete API client's reporting capabilities (#192). This adds the missing piece for managing custom report configurations at the user level.
- New `UserReportSettingsTemplatesResource` class supporting:
- Template listing (with pagination)
- Template creation
- Template retrieval
- Template updates
- Template deletion
- Built as an extension of the base reports architecture
- All tests passing successfully (803 tests total)
- Maintained 95%+ coverage baseline
- Follows project patterns for consistency
- No breaking changes introduced
Implementation validated against official Crowdin API documentation.
Closes #192
=> feat: Add support for User Report Settings Templates endpoints (#192)

crowdin_api/api_resources/enums.py, crowdin_api/api_resources/teams/resource.py, crowdin_api/api_resources/teams/tests/test_teams_resources.py, crowdin_api/api_resources/teams/types.py, crowdin_api/api_resources/users/enums.py, crowdin_api/api_resources/users/resource.py, crowdin_api/api_resources/users/tests/test_users_resources.py, crowdin_api/api_resources/users/types.py
=> feat: add Group Managers and Group Teams API support

crowdin_api/api_resources/teams/resource.py, crowdin_api/api_resources/teams/tests/test_teams_resources.py, crowdin_api/api_resources/users/enums.py, crowdin_api/api_resources/users/resource.py, crowdin_api/api_resources/users/tests/test_users_resources.py, crowdin_api/utils.py
=> feat: Teams and Users API: support more parameters
