crowdin_api/api_resources/languages/resource.py, crowdin_api/api_resources/languages/tests/test_languages_resources.py, crowdin_api/client.py, crowdin_api/requester.py
=> -fix delete api calls

crowdin_api/api_resources/source_files/resource.py
=> add `storageId` params

crowdin_api/api_resources/source_files/resource.py, crowdin_api/api_resources/source_files/tests/test_source_files_resources.py
https://github.com/crowdin/crowdin-api-client-python/issues/8
=> fix https://github.com/crowdin/crowdin-api-client-python/issues/8

crowdin_api/requester.py, crowdin_api/tests/test_requester.py
https://github.com/crowdin/crowdin-api-client-python/issues/6
=> fix https://github.com/crowdin/crowdin-api-client-python/issues/6

crowdin_api/api_resources/tasks/resource.py, crowdin_api/api_resources/tasks/tests/test_tasks_resources.py
This is documented in the API v2 docs -> https://support.crowdin.com/api/v2/#operation/api.projects.tasks.getMany
=> Add support for status filter on list tasks.

crowdin_api/api_resources/__init__.py, crowdin_api/api_resources/reports/resource.py, crowdin_api/api_resources/reports/tests/test_reports_resources.py, crowdin_api/api_resources/reports/types.py, crowdin_api/client.py, crowdin_api/enums.py
fix enterprise reports endpoints
update architectural design for reports
create PlatformType Enum
=> fix enterprise reports endpoint

crowdin_api/api_resources/__init__.py, crowdin_api/api_resources/glossaries/resource.py, crowdin_api/api_resources/glossaries/tests/test_glossaries_resources.py, crowdin_api/api_resources/machine_translation_engines/enums.py, crowdin_api/api_resources/machine_translation_engines/resource.py, crowdin_api/api_resources/machine_translation_engines/tests/test_machine_translation_engines_resources.py, crowdin_api/api_resources/translation_memory/resource.py, crowdin_api/api_resources/translation_memory/tests/test_translation_memory_resources.py, crowdin_api/client.py, crowdin_api/tests/test_client.py
add languageId parameter for api.glossaries.post
add languageId parameter for api.tms.post
add new api-endpoint Machine-Translation-Engines
=> update api glossaries, tm. add api Mts 

crowdin_api/api_resources/__init__.py, crowdin_api/api_resources/groups/enums.py, crowdin_api/api_resources/groups/resource.py, crowdin_api/api_resources/groups/tests/test_groups_resources.py, crowdin_api/api_resources/groups/types.py, crowdin_api/client.py, crowdin_api/tests/test_client.py, crowdin_api/tests/test_client_groups.py
=> add groups endpoint for enterprise

crowdin_api/api_resources/__init__.py, crowdin_api/api_resources/bundles/enums.py, crowdin_api/api_resources/bundles/resource.py, crowdin_api/api_resources/bundles/tests/test_bundles_resources.py, crowdin_api/api_resources/bundles/types.py, crowdin_api/api_resources/distributions/enums.py, crowdin_api/api_resources/distributions/resource.py, crowdin_api/api_resources/distributions/tests/test_distributions_resources.py, crowdin_api/client.py, crowdin_api/tests/test_client.py
add bundles api for base and enterprise platform
update api.projects.distributions.post
=> add bundles api for base and enterprise platform

crowdin_api/api_resources/reports/enums.py, crowdin_api/api_resources/reports/resource.py, crowdin_api/api_resources/reports/tests/test_reports_resources.py, crowdin_api/api_resources/reports/types.py
add report rates templates
add unit tests for reports
=> add report rates templates

crowdin_api/api_resources/__init__.py, crowdin_api/api_resources/teams/enums.py, crowdin_api/api_resources/teams/resource.py, crowdin_api/api_resources/teams/tests/test_teams_resources.py, crowdin_api/api_resources/teams/types.py, crowdin_api/client.py, crowdin_api/tests/test_client.py, crowdin_api/tests/test_client_methods.py
add teams endpoints for enterprise platform
=> add teams endpoints for enterprise platform

crowdin_api/api_resources/glossaries/enums.py, crowdin_api/api_resources/glossaries/resource.py, crowdin_api/api_resources/glossaries/tests/test_glossaries_resources.py, crowdin_api/api_resources/glossaries/types.py
add concept endpoints
add glossaries enums
update terms enums
replace translationOfTermId in conceptId
update add_term method
=> update glossaries apis

README.md, crowdin_api/api_resources/abstract/resources.py, crowdin_api/api_resources/abstract/tests/test_resources.py, crowdin_api/api_resources/bundles/resource.py, crowdin_api/api_resources/dictionaries/resource.py, crowdin_api/api_resources/distributions/resource.py, crowdin_api/api_resources/glossaries/resource.py, crowdin_api/api_resources/groups/resource.py, crowdin_api/api_resources/labels/resource.py, crowdin_api/api_resources/languages/resource.py, crowdin_api/api_resources/machine_translation_engines/resource.py, crowdin_api/api_resources/projects/resource.py, crowdin_api/api_resources/reports/resource.py, crowdin_api/api_resources/screenshots/resource.py, crowdin_api/api_resources/source_files/resource.py, crowdin_api/api_resources/source_strings/resource.py, crowdin_api/api_resources/storages/resource.py, crowdin_api/api_resources/string_comments/resource.py, crowdin_api/api_resources/string_translations/resource.py, crowdin_api/api_resources/tasks/resource.py, crowdin_api/api_resources/teams/resource.py, crowdin_api/api_resources/translation_memory/resource.py, crowdin_api/api_resources/translation_status/resource.py, crowdin_api/api_resources/translations/resource.py, crowdin_api/api_resources/users/resource.py, crowdin_api/api_resources/vendors/resource.py, crowdin_api/api_resources/webhooks/resource.py, crowdin_api/api_resources/workflows/resource.py, crowdin_api/api_resources/workflows/tests/test_workflows_resources.py, crowdin_api/client.py
create with_fetch_all functional
=> create with_fetch_all functional

crowdin_api/api_resources/tasks/resource.py, crowdin_api/api_resources/teams/enums.py, crowdin_api/api_resources/teams/resource.py, crowdin_api/api_resources/teams/tests/test_teams_resources.py, crowdin_api/api_resources/teams/types.py, crowdin_api/api_resources/users/enums.py, crowdin_api/api_resources/users/resource.py, crowdin_api/api_resources/users/tests/test_users_resources.py, crowdin_api/api_resources/users/types.py
update Project Members endpoints
update Teams endpoints
=> Update members and teams api

.github/workflows/pypi.yml, setup.py
hot fix changed python_requires attribute in setup.py
hot fix frozen python build packages version
=> Hot fix pypi

crowdin_api/api_resources/projects/enums.py, crowdin_api/api_resources/projects/resource.py, crowdin_api/api_resources/projects/tests/test_projects_resources.py, crowdin_api/api_resources/projects/types.py
=> feat: Added support for `qaChecksIgnorableCategories`

crowdin_api/api_resources/glossaries/resource.py, crowdin_api/api_resources/glossaries/tests/test_glossaries_resources.py, crowdin_api/api_resources/string_translations/resource.py, crowdin_api/api_resources/string_translations/tests/test_string_translations_resources.py, crowdin_api/api_resources/translation_memory/resource.py, crowdin_api/api_resources/translation_memory/tests/test_translation_memory_resources.py
- Concordance search in glossaries
- Translation alignment
- Concordance search in translation memory
- fix: #74
=> feat: New API endpoints

crowdin_api/api_resources/translation_memory/enums.py, crowdin_api/api_resources/translation_memory/resource.py, crowdin_api/api_resources/translation_memory/tests/test_translation_memory_resources.py, crowdin_api/api_resources/translation_memory/types.py
=> feat: Translation Memory Segments API Suppport

crowdin_api/api_resources/source_files/resource.py, crowdin_api/api_resources/source_files/tests/test_source_files_resources.py
=> feat: Download File Preview

crowdin_api/api_resources/source_files/enums.py, crowdin_api/api_resources/source_files/resource.py, crowdin_api/api_resources/source_files/types.py
=> feat: add javascript file export options

crowdin_api/api_resources/translations/resource.py, crowdin_api/api_resources/translations/tests/test_translations_resources.py
=> feat: add labels to apply pre-translation

crowdin_api/api_resources/source_files/resource.py, crowdin_api/api_resources/source_files/tests/test_source_files_resources.py, crowdin_api/api_resources/source_files/types.py
=> feat: add new source files import options

crowdin_api/api_resources/webhooks/organization/__init__.py, crowdin_api/api_resources/webhooks/organization/enums.py, crowdin_api/api_resources/webhooks/organization/resource.py, crowdin_api/api_resources/webhooks/organization/tests/test_organization_webhooks_resources.py, crowdin_api/api_resources/webhooks/organization/types.py
=> feat(api): add Organization Webhooks API

crowdin_api/api_resources/reports/resource.py, crowdin_api/api_resources/reports/tests/test_reports_resources.py
=> feat: supports for `isPublic` param

crowdin_api/api_resources/__init__.py, crowdin_api/api_resources/fields/__init__.py, crowdin_api/api_resources/fields/enums.py, crowdin_api/api_resources/fields/resource.py, crowdin_api/api_resources/fields/tests/test_fields_resources.py, crowdin_api/api_resources/fields/types.py, crowdin_api/client.py, crowdin_api/tests/test_client.py
=> feat: support for `fields`

crowdin_api/api_resources/projects/enums.py, crowdin_api/api_resources/projects/resource.py, crowdin_api/api_resources/projects/tests/test_projects_resources.py
=> feat(projects): added missing parameters

crowdin_api/api_resources/translations/enums.py, crowdin_api/api_resources/translations/resource.py, crowdin_api/api_resources/translations/tests/test_translations_resources.py, crowdin_api/api_resources/translations/types.py
=> feat(translations): edit, list pre-translations

crowdin_api/api_resources/translations/resource.py, crowdin_api/api_resources/translations/tests/test_translations_resources.py
- New endpoint for generating pre-translation reports
- fixes: #206
=> feat(translations): pre-translation report
